routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('categories' ,'CategoriesController')->middleware('admin');
	Route::resource('title' ,'TitleController')->middleware('admin');
	Route::resource('post' ,'PostsController')->middleware('admin');
	Route::resource('tags' ,'TagsController')->middleware('admin');
	Route::get('trashed_posts' ,'PostsController@trashed')->name('trashed-post.index')->middleware('admin');
	Route::put('restore_posts/{post}' ,'PostsController@restore')->name('restore-posts')->middleware('admin');
	Route::post('gettitle_post', 'GetContentController@gettitle')->name('gettitle-post.index');
	Route::post('getsidebartitle_post', 'GetContentController@getsidetitle')->name('getsidebartitle-post.index');
	Route::post('getcontent_post', 'GetContentController@getcontent')->name('getcontent-post.index');
	Route::get('users/profile','UsersController@edit')->name('users.edit-profile');
	Route::put('users/update','UsersController@update')->name('users.update-profile');
});
Route::middleware(['auth','admin'])->group(function(){
Route::get('users','UsersController@index')->name('users.index');
Route::post('users/{user}/make-admin' ,'UsersController@makeadmin')->name('users.make-admin');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
     public function posts()
    {
    	return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['tags']=Tag::all();
        return view('tags.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request,Tag $tag)
    {
      $tag->name=$request->name;
       $tag->save();
       session()->flash('success','Tag add Success');
       return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
         return view('tags.create')->with('tag',$tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
       public function update(UpdatetagRequest $request,Tag $tag)
    {
        $tag->name=$request->name;
       $tag->save();
       session()->flash('success','Tag Update Success');
       return redirect()->route('tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        if($tag->posts()->count()>0){
              session()->flash('error','Tag Cannot delete beacuse it related to '.$tag->posts()->count().'post');
            return redirect()->back();
        }
        $tag->delete();
        session()->flash('success','tag Deleted Success');
        return redirect()->route('tags.index');
    }
}

resources/views/tags/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-6">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{isset($tag) ? 'Edit tag' :'Create tag'}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
  @include('partials.error')
      <form action="{{isset($tag)? route('tags.update',$tag->id) :route('tags.store')}}" method="post">
        @csrf
        @if(isset($tag))
         @method('PUT')
        @endif
          <div class="form-group">
          <label for='name'>Name</label>
          <input type="text" name="name" class="form-control" value="{{isset($tag)? $tag->name :''}}">
        </div>
        <div clss="form-group">
          <button class="btn {{isset($tag)? 'btn-primary' :'btn-success'}}">
            {{isset($tag)? 'Update tag' :'Add tag'}}
          </button>
        </div>
      </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    </section>
@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">DataTable with default features</h3>
              <a href="{{route('tags.create')}}" class="btn btn-success"  style="float: right;">Add tag</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              @if($tags->count()>0)
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>S.no</th>
                  <th>Name</th>
                  <th>Post Count</th>
                  <th>Action</th>
                </tr>
                </thead>
           <tbody>
             @foreach($tags as $tag)
                <tr>
                  <td>{{ $tag->id }}</td>
                  <td>{{ $tag->name }}</td>
                   <td>{{ $tag->posts->count() }}</td>
                  <td><a href="{{route('tags.edit',$tag->id)}}" class="btn btn-primary"> Edit</a>
                 <button class="btn btn-danger btn-sm" onclick="handledelete({{ $tag->id }})">Delete</button></td>
                </tr>
               @endforeach
                </tbody>
                <tfoot>
                <tr>
                 <th>S.no</th>
                  <th>Name</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
               @else
              <h3 class="text-center">No Post Yet</h3>
              @endif
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </div>
    </section>
          <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
   <form action="" method="POST" id="deletetagForm">
   @method('DELETE')
              @csrf
     <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete tag</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you surely want to delete tag?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No,Go back</button>
        <button type="submit" class="btn btn-danger">Yes,Continuee..</button>
      </div>
    </div>
   </form>
  </div>
</div>

@endsection
@section('script')
<script type="text/javascript">
  function handledelete(id){
    
    var form=document.getElementById('deletetagForm');
    form.action='/tags/'+id;
    $("#deleteModal").modal('show');
  }
</script>
@endsection