routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('categories' ,'CategoriesController')->middleware('admin');
	Route::resource('title' ,'TitleController')->middleware('admin');
	Route::resource('post' ,'PostsController')->middleware('admin');
	Route::resource('tags' ,'TagsController')->middleware('admin');
	Route::get('trashed_posts' ,'PostsController@trashed')->name('trashed-post.index')->middleware('admin');
	Route::put('restore_posts/{post}' ,'PostsController@restore')->name('restore-posts')->middleware('admin');
	Route::post('gettitle_post', 'GetContentController@gettitle')->name('gettitle-post.index');
	Route::post('getsidebartitle_post', 'GetContentController@getsidetitle')->name('getsidebartitle-post.index');
	Route::post('getcontent_post', 'GetContentController@getcontent')->name('getcontent-post.index');
	Route::get('users/profile','UsersController@edit')->name('users.edit-profile');
	Route::put('users/update','UsersController@update')->name('users.update-profile');
});
Route::middleware(['auth','admin'])->group(function(){
Route::get('users','UsersController@index')->name('users.index');
Route::post('users/{user}/make-admin' ,'UsersController@makeadmin')->name('users.make-admin');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;
class Post extends Model
{
	use SoftDeletes;
	public function deleteimage(){
        if($this->image!='avtar1.jpeg'){
        Storage::delete('public/posts/'.$this->image);
    }
    }
     public function category()
    {
    	return $this->belongsTo(Category::class);
    }
    public function title()
    {
    	return $this->belongsTo(Title::class);
    }
      public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
    public function hastags($tagId)
    {
        return  in_array($tagId,$this->tags->pluck('id')->toArray());
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Title;
use App\Category;
use App\Tag;
use App\Post;
use App\Http\Requests\Posts\CreatePostRequest;
use App\Http\Requests\Posts\UpdatePostRequest;
class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
    {
        $this->middleware('verifyCategoriesCount')->only(['store','create']);
    }
    
    public function index()
    {
        $arr['posts']=Post::all();
        return view('posts.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $arr['categories'] = Category::all();
       $arr['titles'] = Title::all();
       $arr['tags']=Tag::all();
       return view('posts.create')->with($arr);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostRequest $request,Post $post)
    {
        $data = Post::where("title_id",$request->title)->get();
        if(count($data)==0){
        if(isset($request->image) && $request->image->getClientOriginalName()){
            $ext =  $request->image->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,99999).'.'.$ext;
            $request->image->storeAs('public/posts',$file);
        }
        else
        {
             if(!$post->image)
                $file = 'avtar1.jpeg';
        }

        $post->image = $file;
        $post->title_id = $request->title;
        $post->category_id = $request->category;
        $post->ptitle = $request->ptitle;
        $post->content = $request->content;
        $post->example = $request->example;
        $post->published_at = $request->published_at;
        $post->potedby = auth()->user()->id;
        $post->save();
        // if($request->tags){
        //     $post->tags()->attach($request->tags);
        // }
        session()->flash('success','Post add Success');
        return redirect()->route('post.index');
    }else{
       session()->flash('error','Post Already Exits');
        return redirect()->route('post.index'); 
    }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
         $arr['categories']=Category::all();
         $arr['titles']=Title::all();
         $arr['tags']=Tag::all();
      return view('posts.create')->with('posts',$post)->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request,Post $post)
    {
       
        if(isset($request->image) && $request->image->getClientOriginalName()){
            $ext =  $request->image->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,99999).'.'.$ext;
            $request->image->storeAs('public/posts',$file);
            $post->deleteimage();
        }
        else
        {
             if(!$post->image)
                $file = 'avtar1.jpeg';
            else
                $file = $post->image;
        }

        $post->image = $file;
        $post->title_id = $request->title;
        $post->category_id = $request->category;
        $post->ptitle = $request->ptitle;
        $post->content = $request->content;
        $post->example = $request->example;
        $post->published_at = $request->published_at;
        $post->potedby = auth()->user()->id;
        $post->save();
        //  if($request->tags){
        //     $post->tags()->sync($request->tags);
        // }
        session()->flash('success','Post Updated Success');
        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post=POST::withTrashed()->where('id',$id)->firstorFail();
        if($post->trashed()){
              $post->deleteimage();
             $post->forceDelete();

        }else{
             $post->delete();
        }
        session()->flash('success','Post Deleted Success');
        return redirect()->route('post.index');
    }

     public function trashed()
    {
         $trashed=Post::onlyTrashed()->get();
          return view('posts.index')->with('posts',$trashed);
    }

        public function restore($id)
    {
        $post=POST::withTrashed()->where('id',$id)->firstorFail();
         $post->restore();
         session()->flash('success','Post Restore Success');
         return redirect()->back();
    }

    

     
}

resources/views/posts/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-6">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{isset($post) ? 'Edit Post' :'Create Post'}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
  @include('partials.error')
        <form action="{{isset($posts)? route('post.update',$posts->id) :route('post.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        @if(isset($posts))
         @method('PUT')
        @endif
         <div class="form-group">
          <label for='name'>Category</label>
            <select name="category" class="form-control" id="category" data-dependent="title">
              <option value="">Choose Category</option>
              @foreach($categories as $c)
                <option value="{{ $c->id }}"
                  @if(isset($posts))
                  @if($c->id == $posts->category_id)
                  selected
                  @endif
                  @endif
                  >{{ $c->name }}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
          <label for='name'>Title</label>
            <select name="title" class="form-control" id="title">
              <option value="">Choose Title</option>
              @foreach($titles as $t)
               
                <option value="{{ $t->id }}"
                  @if(isset($posts))
                  @if($t->id == $posts->title_id)
                  selected
                  @endif
                  @endif
                  >{{ $t->title }}</option>
              @endforeach
            </select>
          </div>
      <!--     @if($tags->count()>0)
        <div class="form-group">
          <label for='tags'>Tag</label>
          <select name="tags[]" id="tags" class="form-control" multiple>
              @foreach($tags as $t)
                <option value="{{ $t->id }}" 
        
        @if(isset($posts))
                  @if($posts->hasTags($t->id))
                  selected
                  @endif
          @endif
                  >
          {{ $t->name }}
          </option>
              @endforeach
        
            </select>
        </div>
        @endif -->
          <div class="form-group">
          <label for='name'>Post Title Description</label>
          <input type="text" name="ptitle" class="form-control" value="{{isset($posts)? $posts->ptitle :''}}">
        </div>
          <div class="form-group">
          <label for='name'>Content</label>
            <input id="content" type="hidden" name="content"  value="{{isset($posts) ? $posts->content : ''}}">
           <trix-editor input="content">
            
           </trix-editor>
        </div>

        <div class="form-group">
          <label for='name'>Example</label>
          <input type="text" class="form-control" id="example" name="example" value="{{isset($posts) ? $posts->example : ''}}">
        </div>
        <div class="form-group" id="checkexample">

        </div>
          <div class="form-group">
          <label for='name'>PublishedAt</label>
          <input type="text" name="published_at" id="published_at" class="form-control" value="{{isset($posts) ? $posts->published_at : ''}}"}}">
        </div>
        <div class="form-group">
          <label for='name'>Image</label>
          @if(isset($posts))
            <div class="form-group">
              <img src='http://www.veltechmultitech.org/cms/storage/app/public/posts/{{$posts->image}}' alt="" style="width: 400px;height: 400px">
            </div>
          @endif
          <input type="file" name="image" id="image" class="form-control">
        </div>
        <div clss="form-group">
          <button class="btn {{isset($post)? 'btn-primary' :'btn-success'}}">
            {{isset($posts)? 'Update Post' :'Add Post'}}
          </button>
        </div>
      </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    </section>
@endsection

@section('script')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.js"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
  <script type="text/javascript">
    flatpickr("#published_at", {
      enableTime: true,
      enableSeconds:true
    });


$(document).ready(function(){
  $('#tags').select2();
 $('#category').change(function(){
  if($(this).val() != '')
  {
   var select = $(this).attr("id");
   var value = $(this).val();
   var dependent = $(this).data('dependent');
   var _token = $('input[name="_token"]').val();
      $.ajax({
    url:"{{ route('gettitle-post.index') }}",
    method:"POST",
    data:{select:select, value:value, _token:_token, dependent:dependent},
    success:function(result)
    {
     
     $('#'+dependent).html(result);
    }

   })
   
  }
 });

 $("#example").bind('blur', function(event) {
  var exa=$(this).val();
  $("#checkexample").html('<iframe height="265" style="width: 100%;" scrolling="no" title="Sample" src="'+exa+'?height=265&theme-id=default&default-tab=html,result" frameborder="no" allowtransparency="true" allowfullscreen="true"></iframe>')
 });
   });
  </script>
@endsection

@section('css')
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.0/trix.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/posts/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Post Master</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              
              <li class="breadcrumb-item active"><a href="{{route('post.index')}}">Post</a></li>
              
              <li class="breadcrumb-item active"><a href="{{route('trashed-post.index')}}">Trashed</a></li>
              
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">DataTable with default features</h3>
              <a href="{{route('post.create')}}" class="btn btn-success"  style="float: right;">Add Post</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              @if($posts->count()>0)
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>S.no</th>
                  <th>Category</th>
                  <th>Title</th>
                  <th>Post Title</th>
                  <th>Image</th>
                  <th>Action</th>
                </tr>
                </thead>
           <tbody>

             @foreach($posts as $post)
                <tr>
                  <td>{{ $post->id }}</td>
                   <td>{{ $post->category->name }}</td>
                    <td>{{ $post->title->title }}</td>
                    <td>{{ $post->ptitle }}</td>
                    <td><img src="storage/app/public/posts/{{$post->image}}" alt="NoImage" style="width:60px;"></td>
                  <td>
                    @if($post->trashed())
                  	 <form action="{{ route('restore-posts',$post->id) }}" method="post">
                   @method('PUT')
                        @csrf
                  <button type='submit' class="btn btn-info btn-sm"> Restore</button>
               </form>
                    @else
                    <a href="{{route('post.edit',$post->id)}}" class="btn btn-primary btn-sm"> Edit</a>
                    @endif
                    <form action="{{route('post.destroy',$post->id)}}" method="post">
                      @method('DELETE')
                       @csrf
                      <button class="btn btn-danger btn-sm"> {{$post->trashed() ? 'Delete' :'Trash'}}</button>
                    </form>
                	 </td>
                </tr>
               @endforeach
                </tbody>
                <tfoot>
                <tr>
                 <th>S.no</th>
                <th>Category</th>
                <th>Title</th>
                <th>Post Title</th>
                 <th>Image</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
              @else
              <h3 class="text-center">No Post Yet</h3>
              @endif
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </div>
    </section>

          <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
   <form action="" method="POST" id="deleteCategoryForm">
   @method('DELETE')
              @csrf
     <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you surely want to delete category?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No,Go back</button>
        <button type="submit" class="btn btn-danger">Yes,Continuee..</button>
      </div>
    </div>
   </form>
  </div>
</div>

@endsection
@section('script')
<script type="text/javascript">
  function handledelete(id){
    
    var form=document.getElementById('deleteCategoryForm');
    form.action='/title/'+id;
    $("#deleteModal").modal('show');
  }
</script>
@endsection