routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('categories' ,'CategoriesController')->middleware('admin');
	Route::resource('title' ,'TitleController')->middleware('admin');
	Route::resource('post' ,'PostsController')->middleware('admin');
	Route::resource('tags' ,'TagsController')->middleware('admin');
	Route::get('trashed_posts' ,'PostsController@trashed')->name('trashed-post.index')->middleware('admin');
	Route::put('restore_posts/{post}' ,'PostsController@restore')->name('restore-posts')->middleware('admin');
	Route::post('gettitle_post', 'GetContentController@gettitle')->name('gettitle-post.index');
	Route::post('getsidebartitle_post', 'GetContentController@getsidetitle')->name('getsidebartitle-post.index');
	Route::post('getcontent_post', 'GetContentController@getcontent')->name('getcontent-post.index');
	Route::get('users/profile','UsersController@edit')->name('users.edit-profile');
	Route::put('users/update','UsersController@update')->name('users.update-profile');
});
Route::middleware(['auth','admin'])->group(function(){
Route::get('users','UsersController@index')->name('users.index');
Route::post('users/{user}/make-admin' ,'UsersController@makeadmin')->name('users.make-admin');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Category extends Model
{
     public function title()
    {
    	return $this->hasMany(Title::class);
    }
    public function posts()
    {
    	return $this->hasMany(Post::class);
    }
    public function deletecatimage(){
        if($this->image!='avtar1.jpeg'){
        Storage::delete('public/category/'.$this->image);
    }
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['categories']=Category::all();
        return view('categories.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request,Category $category)
    {

        if(isset($request->image) && $request->image->getClientOriginalName()){
            $ext =  $request->image->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,99999).'.'.$ext;
            $request->image->storeAs('public/category',$file);

        }
        else
        {
             if(!$category->image)
                $file = 'avtar1.jpeg';
        }

      $category->name=$request->name;
      $category->description=$request->description;
      $category->image = $file;
       $category->save();
       session()->flash('success','Subject add Success');
       return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
         return view('categories.create')->with('category',$category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
       public function update(UpdateCategoryRequest $request,Category $category)
    {

        if(isset($request->image) && $request->image->getClientOriginalName()){
            $ext =  $request->image->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,99999).'.'.$ext;
            $request->image->storeAs('public/category',$file);
            $category->deletecatimage();
        }
        else
        {
             if(!$category->image)
                $file = 'avtar1.jpeg';
            else
                $file = $category->image;
        }
        $category->name=$request->name;
        $category->description=$request->description;
        $category->image = $file;
       $category->save();
       session()->flash('success','Subject Update Success');
       return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        
        if($category->posts()->count()>0){

              session()->flash('error','Subject Cannot delete beacuse it related to '.$category->posts()->count().'post');
            return redirect()->back();
        }
        $category->delete();
        $category->deletecatimage();
        session()->flash('success','Subject Deleted Success');
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-6">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{isset($category) ? 'Edit Subject' :'Create Subject'}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
@include('partials.error')
      <form action="{{isset($category)? route('categories.update',$category->id) :route('categories.store')}}" method="post" enctype="multipart/form-data">
        @csrf
        @if(isset($category))
         @method('PUT')
        @endif
          <div class="form-group">
          <label for='name'>Name</label>
          <input type="text" name="name" class="form-control" value="{{isset($category)? $category->name :''}}">
        </div>
         <div class="form-group">
          <label for='name'>Description</label>
          <input type="text" name="description" class="form-control" value="{{isset($category)? $category->description :''}}">
        </div>
               <div class="form-group">
          <label for='name'>Image</label>
          @if(isset($category))
            <div class="form-group">
              <img src='http://www.veltechmultitech.org/cms/storage/app/public/category/{{$category->image}}' alt="" style="width: 400px;height: 400px">
            </div>
          @endif
          <input type="file" name="image" id="image" class="form-control">
        </div>
        <div clss="form-group">
          <button class="btn {{isset($category)? 'btn-primary' :'btn-success'}}">
            {{isset($category)? 'Update Subject' :'Add Subject'}}
          </button>
        </div>
      </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    </section>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Subject Master</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{{route('categories.index')}}">Subject</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">DataTable with default features</h3>
              <a href="{{route('categories.create')}}" class="btn btn-success"  style="float: right;">Add Subject</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              @if($categories->count()>0)
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>S.no</th>
                  <th>Name</th>
                  <th>PostCount</th>
                  <th>Action</th>
                </tr>
                </thead>
           <tbody>
             @foreach($categories as $category)
                <tr>
                  <td>{{ $category->id }}</td>
                  <td>{{ $category->name }}</td>
                  <td>{{ $category->posts()->count()  }}</td>
                  <td><a href="{{route('categories.edit',$category->id)}}" class="btn btn-primary"> Edit</a>
                 <button class="btn btn-danger btn-sm" onclick="handledelete({{ $category->id }})">Delete</button></td>
                </tr>
               @endforeach
                </tbody>
                <tfoot>
                <tr>
                 <th>S.no</th>
                  <th>Name</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
               @else
              <h3 class="text-center">No Post Yet</h3>
              @endif
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    </section>
          <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
   <form action="" method="POST" id="deleteCategoryForm">
   @method('DELETE')
              @csrf
     <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you surely want to delete category?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No,Go back</button>
        <button type="submit" class="btn btn-danger">Yes,Continuee..</button>
      </div>
    </div>
   </form>
  </div>
</div>

@endsection
@section('script')
<script type="text/javascript">
  function handledelete(id){
    
    var form=document.getElementById('deleteCategoryForm');
    form.action='categories/'+id;
    $("#deleteModal").modal('show');
  }
</script>
@endsection