routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
	Route::get('/home', 'HomeController@index')->name('home');
	Route::resource('categories' ,'CategoriesController')->middleware('admin');
	Route::resource('title' ,'TitleController')->middleware('admin');
	Route::resource('post' ,'PostsController')->middleware('admin');
	Route::resource('tags' ,'TagsController')->middleware('admin');
	Route::get('trashed_posts' ,'PostsController@trashed')->name('trashed-post.index')->middleware('admin');
	Route::put('restore_posts/{post}' ,'PostsController@restore')->name('restore-posts')->middleware('admin');
	Route::post('gettitle_post', 'GetContentController@gettitle')->name('gettitle-post.index');
	Route::post('getsidebartitle_post', 'GetContentController@getsidetitle')->name('getsidebartitle-post.index');
	Route::post('getcontent_post', 'GetContentController@getcontent')->name('getcontent-post.index');
	Route::get('users/profile','UsersController@edit')->name('users.edit-profile');
	Route::put('users/update','UsersController@update')->name('users.update-profile');
});
Route::middleware(['auth','admin'])->group(function(){
Route::get('users','UsersController@index')->name('users.index');
Route::post('users/{user}/make-admin' ,'UsersController@makeadmin')->name('users.make-admin');
});

app/Title.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Title extends Model
{
    public function category()
    {
    	return $this->belongsTo(Category::class);
    }
    public function posts()
    {
    	return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/TitleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Title;
use App\Category;
use App\Http\Requests\Title\CreateTitleRequest;
use App\Http\Requests\Title\UpdateTitleRequest;
class TitleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $arr['titles']=Title::all();
         return view('title.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $arr['categories'] = Category::all();
         return view('title.create')->with($arr);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
     public function store(CreateTitleRequest $request,Title $title)
    {
        $title->title=$request->name;
        $title->category_id =$request->category;
        $title->save();
        session()->flash('success','Title add Success');
        return redirect()->route('title.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Title $title)
    {
        $arr['categories'] = Category::all();
       return view('title.create')->with('title',$title)->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTitleRequest $request,Title $title)
    {
        $title->title=$request->name;
        $title->category_id =$request->category;
        $title->save();
        session()->flash('success','Title Updated Success');
        return redirect()->route('title.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Title $title)
    {
        if($title->posts()->count()>0){
              session()->flash('error','Tag Cannot delete beacuse it related to '.$title->posts()->count().'post');
            return redirect()->back();
        }
        $title->delete();
        session()->flash('success','Title Deleted Success');
        return redirect()->route('title.index');
    }
}

resources/views/title/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-6">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{isset($title) ? 'Edit Title' :'Create Title'}}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
@include('partials.error')
      <form action="{{isset($title)? route('title.update',$title->id) :route('title.store')}}" method="post">
        @csrf
         @if(isset($title))
         @method('PUT')
        @endif
         <div class="form-group">
          <label for='name'>Category</label>
            <select name="category" class="form-control">
              <option value="">Choose Category</option>
              @foreach($categories as $c)
               
                <option value="{{ $c->id }}"
                  @if(isset($title))
                  @if($c->id == $title->category_id)
                  selected
                  @endif
                  @endif
                  >{{ $c->name }}</option>
              @endforeach
            </select>
          </div>
          <div class="form-group">
          <label for='name'>Name</label>
          <input type="text" name="name" class="form-control" value="{{isset($title)? $title->title :''}}">
        </div>
        <div clss="form-group">
          <button class="btn {{isset($title)? 'btn-primary' :'btn-success'}}">
            {{isset($title)? 'Update Title' :'Add Title'}}
          </button>
        </div>
      </form>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    </section>
@endsection

resources/views/title/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Title Master</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{{route('title.index')}}">Title</a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid" id="fetch_Content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">DataTable with default features</h3>
              <a href="{{route('title.create')}}" class="btn btn-success"  style="float: right;">Add Title</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              @if($titles->count()>0)
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>S.no</th>
                  <th>Category</th>
                  <th>Title</th>
                  <th>Action</th>
                </tr>
                </thead>
           <tbody>
             @foreach($titles as $title)
                <tr>
                  <td>{{ $title->id }}</td>
                  <td>{{ $title->category->name }}</td>
                  <td>{{ $title->title }}</td>
                  <td><a href="{{route('title.edit',$title->id)}}" class="btn btn-primary"> Edit</a>
                 <button class="btn btn-danger btn-sm" onclick="handledelete({{ $title->id }})">Delete</button></td>
                </tr>
               @endforeach
                </tbody>
                <tfoot>
                <tr>
                 <th>S.no</th>
                 <th>Category</th>
                  <th>Name</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
               @else
              <h3 class="text-center">No Post Yet</h3>
              @endif
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div>
    </section>

          <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
   <form action="" method="POST" id="deleteCategoryForm">
   @method('DELETE')
              @csrf
     <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you surely want to delete category?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No,Go back</button>
        <button type="submit" class="btn btn-danger">Yes,Continuee..</button>
      </div>
    </div>
   </form>
  </div>
</div>

@endsection
@section('script')
<script type="text/javascript">
  function handledelete(id){
    
    var form=document.getElementById('deleteCategoryForm');
    form.action='title/'+id;
    $("#deleteModal").modal('show');
  }
</script>
@endsection